name:                cd-blog
version:             0.1.0.0
github:              "cdornan/cd-blog"
license:             OtherLicense
author:              "Chris Dornan"
maintainer:          "chris@chrisdornan.com"
copyright:           "2019-2020 Chris Dornan"

synopsis:            chrisdornan.com blog
category:            Network

description:         chrisdornan.com Hakyll blog

dependencies:
- base == 4.*
- hakyll
- hakyll-images
- hakyll-sass
- hsass
- data-default

ghc-options:
- -Wall
- -fwarn-tabs

executables:
   cd-blog:
    main: site.hs
    ghc-options:
    - -threaded
    dependencies: []
