name:                cd-blog
version:             0.1.0.0
github:              "cdornan/cd-blog"
license:             OtherLicense
author:              "Chris Dornan"
maintainer:          "chris@chrisdornan.com"
copyright:           "2019-2020 Chris Dornan"

synopsis:            chrisdornan.com blog
category:            Network

description:         chrisdornan.com Hakyll blog

dependencies:
- base == 4.*
- array
- containers
- data-default
- enum-text
- filepath
- fmt
- hakyll
- hakyll-images
- hakyll-sass
- heredoc
- hsass
- hashable
- text
- time
- unordered-containers

ghc-options:
- -Wall
- -fwarn-tabs

library:
  source-dirs: src

executables:
  cd-blog:
    main:          cd-blog.hs
    source-dirs:   app
    ghc-options:
    - -threaded
    dependencies:
    - cd-blog
