resolver: lts-14.27

ghc-options:
  cd-blog: -Werror

allow-newer: true

packages:
- .

extra-deps:
- pandoc-2.7.3
- pandoc-citeproc-0.16.2
- ipynb-0.1
- hakyll-4.12.5.2
- hakyll-images-0.4.4
- hakyll-sass-0.2.4
- lrucache-1.2.0.1
